theme: jekyll-theme-minimal
title: marigombae's homepage
<p align="center">
  <img src="https://capsule-render.vercel.app/api?text=Welcome to marigombae's page!ðŸ•¹ï¸&animation=fadeIn&type=waving&color=gradient&height=100"/>
</p>
![Kirby sitting on a star while waving](file:///Users/marigomezbaeza/Downloads/Kirby%20(2).svg)
description: Bookmark this to keep an eye on my project updates!
