remote_theme: CalinRadoni/simple-purple-theme
title: 
 <p align="center">
    <img src="https://img.freepik.com/free-vector/neon-grid-background_53876-91657.jpg?w=1800&t=st=1726598336~exp=1726598936~hmac=7a03c4dd452ce730f47ca0f1831f90d7dff6dbd2f2190c9003358b21e959cbcctext=Welcome to marigombae's homepage!ðŸ•¹ï¸&animation=fadeIn&type=waving&color=gradient&height=100"/>
  </p>
![Kirby sitting on a star while waving](https://raw.githubusercontent.com/marigombae/marigombae.github.io/8f7c4ae4d85d8be395587db37e74377e927656d8/Kirby%20(2).svg)
description: Bookmark this to keep an eye on my project updates!
